# Conda environment for running the project on the VSC HPC cluster.
# Create with:   conda env create -f environment.yml
# Activate with: conda activate bloomfilter_analysis

name: bloomfilter_analysis

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - numpy
  - matplotlib
  - openssl
  - pytest

  - pip:
      - bitarray>=2.0.0
      - mmh3==5.2.1
